FROM golang:1.15-alpine

RUN apk add git bash build-base && \
    go get -u github.com/gobuffalo/packr/v2/packr2

COPY . /go/src/github.com/ory/hydra

ARG VERSION=unknown
ARG REVISION=unknown
ARG CGO_ENABLED=0

WORKDIR /go/src/github.com/ory/hydra

RUN VERSION=${VERSION} REVISION=${REVISION} CGO_ENABLED=${CGO_ENABLED} make build
